# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  bukuniversalgamesapi:
    image: bukuniversalgamesapi
    build:
      context: .
      dockerfile: backend/Buk.UniversalGames.Api/Dockerfile
    ports:
      - 5125:5125
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_DB=buk-universal-games
      - POSTGRES_USER=admin
      - POSTGRES_HOST=database
      - POSTGRES_PASSWORD=password
      - ASPNETCORE_ENVIRONMENT=Development
      - REDIS_CONNECTION_STRING=redis:6379
      - ENVIRONMENT_NAME=local
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
    depends_on:
      - database
     # - redis
    restart: on-failure:5

  redis:
    image: redis:6.2-alpine
    restart: always
    # ports:
    #   - '6379:6379'
  #  command: redis-server --requirepass redispw
  #   # volumes: 
  #   #   - .data/cache:/data

  
  database:
    container_name: bukuniversalgames_database
    image: postgis/postgis:13-master
    volumes:
      - ./.data/database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=buk-universal-games
    ports:
      - "5432:5432"

  pgadmin: #connect using host.docker.internal as host on windows
      container_name: bukuniversalgames_pgadmin4
      image: dpage/pgadmin4
      restart: always
      environment:
        - PGADMIN_DEFAULT_USERNAME=admin
        - PGADMIN_DEFAULT_EMAIL=admin@admin.com
        - PGADMIN_DEFAULT_PASSWORD=password
      ports:
        - "5126:80"
